name: Build AEX Video Player APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip git zip unzip openjdk-17-jdk
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Install Android SDK (cmdline-tools)
        run: |
          mkdir -p ~/.buildozer/android/platform
          cd ~/.buildozer/android/platform
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip
          mkdir -p android-sdk/cmdline-tools/latest
          mv cmdline-tools/* android-sdk/cmdline-tools/latest/
          export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses || true
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --update

      - name: Accept Android SDK licenses
        run: |
          export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Set environment variables
        run: |
          echo "export PATH=$PATH:$HOME/.local/bin" >> $GITHUB_ENV
          echo "export ANDROIDSDK=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
          echo "export ANDROIDNDK=$HOME/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV
          echo "export ANDROIDAPI=33" >> $GITHUB_ENV
          echo "export NDKAPI=21" >> $GITHUB_ENV

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: AEX-Video-Player-APK
          path: bin/*.apk
